# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
