# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(default='novel', max_length=250),
            preserve_default=False,
        ),
    ]
